### ISSUE TITLE
Disambiguation -> Add a threshold that triggers fallback

### ISSUE THREAD

**Issue by znat** [mrbot-ai/rasa-addons#6]
Define a criterion that would trigger fallback immediately, skipping disambiguation. 

```
disambiguation_policy:
  nlu:
    trigger: $0 < 2 * $1
    display:
      type: text_with_buttons
      intro_template: utter_disamb_intro
      text_template: utter_disamb_text
      button_title_template_prefix: utter_disamb
      fallback_title: utter_fallback
      fallback_payload: /fallback
      max_suggestions: 2
```
We could have:

```
disambiguation_policy:
  nlu:
    fallback:
        trigger: $0 < 0.5
        display:
            text: utter_fallback_intro
            buttons:
                - title: utter_fallback_yes
                   payload: /fallback
                - title: utter_fallback_no
                   payload: /restart       
    disambiguation:
        trigger: $0 < 2 * $1
        max_suggestions: 2
        display:
            intro_template: utter_disamb_intro
            text_template: utter_disamb_text
            button_title_template_prefix: utter_disamb
            fallback_button:
                   title: utter_fallback_yes
                   payload: /fallback
```

The `fallback_payload` could be moved to the `nlu` level since it would not depend on the display options anymore
